<!-- ================================= JavaScript BackGround Cover Slide =============================== -->

                <script src="js/jquery-3.4.1.min.js"></script>
	        <script src="js/jquery.fadeshow-0.1.2.min.js" type="text/javascript"></script>
	        <script type="text/javascript">
	            $(function(){
		            var fadeShow = $(".background").fadeShow({
			        correctRatio: true,
			        shuffle: true,
			        speed: 7000,
			        images: ['images/covers/image0.jpg',
					         'images/covers/image1.jpg',
					         'images/covers/image2.jpg',
					         'images/covers/image3.jpg',
							 'images/covers/image4.jpg',
							 'images/covers/image5.jpg',
							 'images/covers/image6.jpg',
							 'images/covers/image7.jpg',
							 'images/covers/image8.jpg',
							 'images/covers/image9.jpg',
							 'images/covers/image10.jpg',
							 'images/covers/image11.jpg',
							 'images/covers/image12.jpg',
							 'images/covers/image13.jpg',
							 'images/covers/image14.jpg',
							 'images/covers/image15.jpg',
							 'images/covers/image16.jpg',
							 'images/covers/image17.jpg',
							 'images/covers/image18.jpg',
							 'images/covers/image19.jpg',
							 'images/covers/image20.jpg',
							 'images/covers/image21.jpg',
							 'images/covers/image22.jpg',
							 'images/covers/image23.jpg',
							 'images/covers/image24.jpg',
							 'images/covers/image25.jpg',
							 'images/covers/image26.jpg',
							 'images/covers/image27.jpg',
							 'images/covers/image28.jpg',
							 'images/covers/image29.jpg',
							 'images/covers/image30.jpg',
							 'images/covers/image31.jpg',
							 'images/covers/image32.jpg',
							 'images/covers/image33.jpg',
							 'images/covers/image34.jpg',
							 'images/covers/image35.jpg',
							 'images/covers/image36.jpg',
							 'images/covers/image37.jpg',
							 'images/covers/image38.jpg',
							 'images/covers/image39.jpg',
							 'images/covers/image40.jpg',
							 'images/covers/image41.jpg',
							 'images/covers/image42.jpg',
							 'images/covers/image43.jpg',
							 'images/covers/image44.jpg',
							 'images/covers/image45.jpg',
                             'images/covers/image46.jpg',
                             'images/covers/image47.jpg',
                             'images/covers/image48.jpg',
                             'images/covers/image49.jpg',
                             'images/covers/image50.jpg', 
                             'images/covers/image51.jpg',							 
					         'images/covers/image52.jpg']
		            });
	            });
	    </script>
